## Supported layouts:
# even-horizontal:          Panes are spread out evenly from left to right across the window.
# even-vertical:            Panes are spread evenly from top to bottom.
# main-horizontal:          A large (main) pane is shown at the top of the window and the remaining panes are spread from left to right in the leftover space at the bottom. Use the main-pane-height window option to specify the height of the top pane.
# main-horizontal-mirrored: The same as main-horizontal but mirrored so the main pane is at the bottom of the window.
# main-vertical:            A large (main) pane is shown on the left of the window and the remaining panes are spread from top to bottom in the leftover space on the right. Use the main-pane-width window option to specify the width of the left pane.
# main-vertical-mirrored:   The same as main-vertical but mirrored so the main pane is on the right of the window.
# tiled:                    Panes are spread out as evenly as possible over the window in both rows and columns. 
name: simulation
root: ./
pre_window: source shell_additions.sh
startup_window: planner/matlab
windows:
  - core/gz:
      layout: tiled
      panes:
        - roscore
        - waitForRos; roslaunch mission_planner world.launch world:=pv_farm
  - planner/matlab: 
      layout: main-vertical
      panes:
        - waitForRos; roslaunch mission_planner planner.launch
        #- waitForRos; roscd mission_planner; rostopic echo /heuristic_planning/result
        - waitForRos; roscd mission_planner; cd scripts; matlab -nodisplay -nosplash -r "matlab_ros_connector; exit"
        - roscd mission_planner
  - uav1:
      layout: main-vertical
      panes:
        - waitForRos; roslaunch mission_planner agent.launch id:=1 type:=InspectionACW
        - waitForRos; roslaunch mission_planner ual.launch ual_backend:=light material:=Green id:=1 x:=0 y:=0 z:=0 robot_model:=mbzirc robot_package:=robots_description camera:=false max_horizontal_velocity:=3
        - waitForRos; roslaunch mission_planner battery_faker.launch id:=1 battery_mode:=recharge_in_base
        #- waitForSimulation; rosrun groot Groot &; roscd mission_planner
  - uav2:
      layout: main-vertical
      panes:
        - waitForRos; roslaunch mission_planner agent.launch id:=2 type:=InspectionACW
        - waitForRos; roslaunch mission_planner ual.launch ual_backend:=light material:=Orange id:=2 x:=0 y:=5 z:=0 robot_model:=mbzirc robot_package:=robots_description camera:=false max_horizontal_velocity:=3
        - waitForRos; roslaunch mission_planner battery_faker.launch id:=2 battery_mode:=recharge_in_base
        #- waitForSimulation; rosrun groot Groot &; roscd mission_planner
  - uav3:
      layout: main-vertical
      panes:
        - waitForRos; roslaunch mission_planner agent.launch id:=3 type:=InspectionACW
        - waitForRos; roslaunch mission_planner ual.launch ual_backend:=light material:=Red id:=3 x:=0 y:=-5 z:=0 robot_model:=mbzirc robot_package:=robots_description camera:=false  max_horizontal_velocity:=3
        - waitForRos; roslaunch mission_planner battery_faker.launch id:=3 battery_mode:=recharge_in_base
        - waitForRos; rosrun mission_planner ist_ugv_faker
        #- waitForSimulation; rosrun groot Groot &; roscd mission_planner